version: "3.8"

services:
  db:
    image: postgres:15
    container_name: shopify-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopify_demo
    ports:
      - "5433:5432"   # <— changed host port to 5433
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
